services:
  # MongoDB
  cadmus-tes-mongo:
    image: mongo:4.4
    platform: linux/amd64
    container_name: cadmus-tes-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - cadmus-tes-network

  # PostgreSQL
  cadmus-tes-pgsql:
    image: postgres
    container_name: cadmus-tes-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5433:5432
    networks:
      - cadmus-tes-network

  # Cadmus TES API
  cadmus-tes-api:
    image: vedph2020/cadmus-tes-api:0.0.1
    platform: linux/amd64
    container_name: cadmus-tes-api
    ports:
      - 5101:8080
    depends_on:
      - cadmus-tes-mongo
      - cadmus-tes-pgsql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-tes-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-tes-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-tes-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__MOL=Server=cadmus-tes-pgsql;port=5432;Database=mol;User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-tes-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__DELAY=20
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
    networks:
      - cadmus-tes-network

  # Cadmus TES App
  cadmus-tes-app:
    image: vedph2020/cadmus-tes-app:0.0.1
    platform: linux/amd64
    container_name: cadmus-tes-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-tes-api
    networks:
      - cadmus-tes-network

networks:
  cadmus-tes-network:
    driver: bridge
